# Generated by Django 4.2.4 on 2024-08-01 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 14, 52, 31, 381760)),
        ),
    ]
