# Generated by Django 4.2.4 on 2024-05-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='remind_every',
        ),
    ]
