# Generated by Django 4.2.4 on 2024-08-01 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0003_alter_task_date_added_alter_task_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 16, 17, 30, 855552)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
