# Generated by Django 4.2.4 on 2024-05-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0005_alter_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
