# Generated by Django 4.2.4 on 2024-08-01 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0005_alter_task_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 19, 6, 21, 46654)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, default='01082024190620', editable=False, max_length=50, null=True, unique=True),
        ),
    ]
