# Generated by Django 4.2.4 on 2024-05-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0006_alter_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
