# Generated by Django 4.2.4 on 2024-08-02 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0007_alter_task_submission_date_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 17, 58, 46, 261461)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
