# Generated by Django 4.2.4 on 2024-08-03 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0008_alter_task_submission_date_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 3, 46, 10, 118343)),
        ),
    ]
