# Generated by Django 4.2.4 on 2024-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0009_remove_employee_company_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='TO_BE_ASSIGNED', max_length=100),
        ),
    ]
