# Generated by Django 4.2.4 on 2024-05-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0010_remove_employee_user_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='remind_every',
            field=models.DurationField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MITR_app.employee'),
        ),
    ]
