# Generated by Django 4.2.4 on 2024-05-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0011_remove_task_user_task_remind_every_alter_task_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remind_every',
            field=models.DurationField(default=2),
        ),
    ]
