# Generated by Django 4.2.4 on 2024-08-07 21:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0011_task_completed_at_task_completed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rework_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reworked_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='rework_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 2, 37, 9, 689888)),
        ),
    ]
