# Generated by Django 4.2.4 on 2024-05-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0012_alter_task_remind_every'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remind_every',
            field=models.DurationField(),
        ),
    ]
