# Generated by Django 4.2.4 on 2024-05-19 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0013_alter_task_remind_every'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 1, 1, 40, 585034)),
        ),
        migrations.AddField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 1, 1, 40, 585034)),
        ),
    ]
