# Generated by Django 4.2.4 on 2024-05-19 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0015_task_completed_alter_task_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 2, 7, 26, 316875)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 2, 7, 26, 316875)),
        ),
    ]
