# Generated by Django 4.2.4 on 2024-05-22 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0016_task_client_company_alter_task_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 22, 17, 4, 468487)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 22, 17, 4, 468487)),
        ),
    ]
