# Generated by Django 4.2.4 on 2024-05-22 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0018_alter_task_date_added_alter_task_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 1, 19, 28, 754398)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 1, 19, 28, 754398)),
        ),
    ]
