# Generated by Django 4.2.4 on 2024-05-27 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0021_alter_task_date_added_alter_task_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee_marked_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 22, 6, 35, 332468)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 22, 6, 35, 332468)),
        ),
    ]
