# Generated by Django 4.2.4 on 2024-05-27 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0022_task_employee_marked_completed_alter_task_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 22, 48, 9, 309697)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 22, 48, 9, 309697)),
        ),
    ]
