# Generated by Django 4.2.4 on 2024-05-27 21:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0024_alter_customuser_is_superuser_alter_task_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_reminder_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 3, 23, 17, 367545)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 28, 3, 23, 17, 366544)),
        ),
    ]
