# Generated by Django 4.2.4 on 2024-07-03 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0033_alter_task_date_added_alter_task_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 15, 26, 41, 484886)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 15, 26, 41, 484886)),
        ),
    ]
