# Generated by Django 4.2.4 on 2024-07-08 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0035_alter_task_date_added_alter_task_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_phone_number',
            field=models.IntegerField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 7, 9, 0, 58, 42, 225785)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 9, 0, 58, 42, 225785)),
        ),
    ]
