# Generated by Django 4.2.4 on 2024-07-17 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MITR_app', '0036_task_client_phone_number_alter_task_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 1, 59, 41, 949029)),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 1, 59, 41, 949029)),
        ),
    ]
